name: Extract version tags
description: Calculates and sets VERSION and FILE_VERSION environment variables based on git tags and hash.
runs:
  using: "composite"
  steps:
  - name: Extract git hash
    shell: bash
    run: |
        # Get short git hash and convert to numeric only value
        GIT_HASH=$(git rev-parse --short HEAD)
        # Convert hex hash to decimal and apply modulo 65536
        GIT_REVISION_NUM=$(( $(printf "%d" 0x$GIT_HASH) % 65536 ))
        echo "GIT_HASH=$GIT_HASH" >> $GITHUB_ENV
        echo "GIT_REVISION_NUM=$GIT_REVISION_NUM" >> $GITHUB_ENV
        echo "Git hash is: $GIT_HASH (numeric value $GIT_REVISION_NUM)"

  - name: Extract version from last tag
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    shell: bash
    run: |
        TAG=$(git describe --tags --abbrev=0 --match "v*" || echo "")
        # Extract base version (v1.2.0 from v1.2.0-beta.2 or v1.2.0)
        BASE_TAG=$(echo "$TAG" | grep -oE '^v[0-9]+\.[0-9]+\.[0-9]+')
        # Strip leading v if present
        BASE_TAG_STRIPPED=$(echo "$BASE_TAG" | sed 's/^v//')
        # Compose version string
        if [ -n "$BASE_TAG_STRIPPED" ]; then
          VERSION="${BASE_TAG_STRIPPED}-next+build${{ env.GIT_REVISION_NUM }}"
          FILE_VERSION="${BASE_TAG_STRIPPED}.${{ env.GIT_REVISION_NUM }}"
        else
          VERSION="0.0.0-next+build${{ env.GIT_REVISION_NUM }}"
          FILE_VERSION="0.0.0.${{ env.GIT_REVISION_NUM }}"
        fi
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "FILE_VERSION=$FILE_VERSION" >> $GITHUB_ENV
        echo "Calculated version is: $VERSION"
        echo "Calculated file version is: $FILE_VERSION"

  - name: Extract version from tag
    if: startsWith(github.ref, 'refs/tags/')
    shell: bash
    run: |
        VERSION="${GITHUB_REF#refs/tags/v}"
        BASE_VERSION=$(echo "${GITHUB_REF#refs/tags/v}" | grep -oE '^[0-9]+\.[0-9]+\.[0-9]+')
        FILE_VERSION="${BASE_VERSION}.${{ env.GIT_REVISION_NUM }}"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "FILE_VERSION=$FILE_VERSION" >> $GITHUB_ENV
        echo "Calculated version is: $VERSION"
        echo "Calculated file version is: $FILE_VERSION"