name: Prepare environment
description: Prepare the environment for building .NET projects.
runs:
  using: "composite"
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - uses: ./.github/actions/extract-version-tags
        
    - name: Restore dependencies
      shell: bash
      run: dotnet restore /p:EnableWindowsTargeting=true /p:Version=${{ env.VERSION }} /p:FileVersion=${{ env.FILE_VERSION }} /p:AssemblyVersion=${{ env.FILE_VERSION }}
   